package com.fly.fankun.model.entity;

import java.util.Date;

public class MyExam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_exam.id
     *
     * @mbggenerated Fri Oct 18 20:10:47 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_exam.exam_id
     *
     * @mbggenerated Fri Oct 18 20:10:47 CST 2019
     */
    private Integer examId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_exam.person_id
     *
     * @mbggenerated Fri Oct 18 20:10:47 CST 2019
     */
    private Integer personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_exam.status
     *
     * @mbggenerated Fri Oct 18 20:10:47 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_exam.create_time
     *
     * @mbggenerated Fri Oct 18 20:10:47 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_exam.update_time
     *
     * @mbggenerated Fri Oct 18 20:10:47 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_exam.deleted
     *
     * @mbggenerated Fri Oct 18 20:10:47 CST 2019
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_exam.id
     *
     * @return the value of my_exam.id
     *
     * @mbggenerated Fri Oct 18 20:10:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_exam.id
     *
     * @param id the value for my_exam.id
     *
     * @mbggenerated Fri Oct 18 20:10:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_exam.exam_id
     *
     * @return the value of my_exam.exam_id
     *
     * @mbggenerated Fri Oct 18 20:10:47 CST 2019
     */
    public Integer getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_exam.exam_id
     *
     * @param examId the value for my_exam.exam_id
     *
     * @mbggenerated Fri Oct 18 20:10:47 CST 2019
     */
    public void setExamId(Integer examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_exam.person_id
     *
     * @return the value of my_exam.person_id
     *
     * @mbggenerated Fri Oct 18 20:10:47 CST 2019
     */
    public Integer getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_exam.person_id
     *
     * @param personId the value for my_exam.person_id
     *
     * @mbggenerated Fri Oct 18 20:10:47 CST 2019
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_exam.status
     *
     * @return the value of my_exam.status
     *
     * @mbggenerated Fri Oct 18 20:10:47 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_exam.status
     *
     * @param status the value for my_exam.status
     *
     * @mbggenerated Fri Oct 18 20:10:47 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_exam.create_time
     *
     * @return the value of my_exam.create_time
     *
     * @mbggenerated Fri Oct 18 20:10:47 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_exam.create_time
     *
     * @param createTime the value for my_exam.create_time
     *
     * @mbggenerated Fri Oct 18 20:10:47 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_exam.update_time
     *
     * @return the value of my_exam.update_time
     *
     * @mbggenerated Fri Oct 18 20:10:47 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_exam.update_time
     *
     * @param updateTime the value for my_exam.update_time
     *
     * @mbggenerated Fri Oct 18 20:10:47 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_exam.deleted
     *
     * @return the value of my_exam.deleted
     *
     * @mbggenerated Fri Oct 18 20:10:47 CST 2019
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_exam.deleted
     *
     * @param deleted the value for my_exam.deleted
     *
     * @mbggenerated Fri Oct 18 20:10:47 CST 2019
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}